# version: '3'
# services:
#   mysqlcontainer:
#     image: mysql:latest
#     ports:
#       - 8080:3036
#     volumes:
#       - ./test-sql-2:/docker-entrypoint-initdb.d
#     environment:
#       MYSQL_ROOT_PASSWORD: pwdtest
#       MYSQL_DATABASE: mysql